syntax = "proto3";

package mail;

option go_package = "duif/proto";

import "google/protobuf/struct.proto";

service MailService {
    rpc SendEmail (EmailRequest) returns (EmailResponse);
    rpc GetEmail (GetEmailRequest) returns (Email);
    rpc GetAllEmails (GetAllEmailsRequest) returns (GetAllEmailsResponse);
    rpc ListTemplates (ListTemplatesRequest) returns (ListTemplatesResponse);
}

message EmailRequest {
    string to = 1;
    string from = 2;
    string subject = 3;
    string body = 4;
    bool is_html = 5;
    string reply_to = 6;
    string cc = 7;
    string template_id = 8;
    map<string, google.protobuf.Value> template_data = 9;
}

message EmailResponse {
    bool success = 1;
    string message = 2;
    string email_id = 3;
}

message GetEmailRequest {
    string id = 1;
}

message GetAllEmailsRequest {}

message Email {
    string id = 1;
    string to = 2;
    string from = 3;
    string subject = 4;
    string body = 5;
    string status = 6;
    string created_at = 7;
    string sent_at = 8;
}

message GetAllEmailsResponse {
    repeated Email emails = 1;
    int32 count = 2;
}

message ListTemplatesRequest {}

message Template {
    string id = 1;
    string name = 2;
    string subject = 3;
    bool is_html = 4;
    string created_at = 5;
    string updated_at = 6;
}

message ListTemplatesResponse {
    repeated Template templates = 1;
    int32 count = 2;
}
